swagger: '2.0'
info:
  title: '"Where are my friends?" API'
  description: Specification for the backend project application "Where are my friends?"
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /jwt/create/:
    post:
      operationId: jwt_create_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenObtainPair'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenObtainPair'
      tags:
      - jwt
    parameters: []
  /jwt/refresh/:
    post:
      operationId: jwt_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenRefresh'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenRefresh'
      tags:
      - jwt
    parameters: []
  /jwt/verify/:
    post:
      operationId: jwt_verify_create
      description: |-
        Takes a token and indicates if it is valid.  This view provides no
        information about a token's fitness for a particular use.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenVerify'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenVerify'
      tags:
      - jwt
    parameters: []
  /tags/:
    get:
      operationId: tags_list
      description: Вьюсет для модели Тегов.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Tag'
      tags:
      - tags
    parameters: []
  /tags/{id}/:
    get:
      operationId: tags_read
      description: Вьюсет для модели Тегов.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Tag'
      tags:
      - tags
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Интерес.
      required: true
      type: integer
  /users/:
    get:
      operationId: users_list
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: tags
        in: query
        description: ''
        required: false
        type: string
      - name: search
        in: query
        description: A search term.
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CustomUser'
      tags:
      - users
    post:
      operationId: users_create
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUserCreate'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CustomUserCreate'
      tags:
      - users
    parameters: []
  /users/activation/:
    post:
      operationId: users_activation
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Activation'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Activation'
      tags:
      - users
    parameters: []
  /users/all-requests/:
    get:
      operationId: users_all_requests
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: tags
        in: query
        description: ''
        required: false
        type: string
      - name: search
        in: query
        description: A search term.
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CustomUser'
      tags:
      - users
    parameters: []
  /users/friends/:
    get:
      operationId: users_friends
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: tags
        in: query
        description: ''
        required: false
        type: string
      - name: search
        in: query
        description: A search term.
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CustomUser'
      tags:
      - users
    parameters: []
  /users/me/:
    get:
      operationId: users_me_read
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: tags
        in: query
        description: ''
        required: false
        type: string
      - name: search
        in: query
        description: A search term.
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CustomUser'
      tags:
      - users
    put:
      operationId: users_me_update
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUser'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    patch:
      operationId: users_me_partial_update
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUser'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    delete:
      operationId: users_me_delete
      description: Кастомный вьюсет для работы с пользователем.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - users
    parameters: []
  /users/resend_activation/:
    post:
      operationId: users_resend_activation
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
      - users
    parameters: []
  /users/reset_password/:
    post:
      operationId: users_reset_password
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
      - users
    parameters: []
  /users/reset_password_confirm/:
    post:
      operationId: users_reset_password_confirm
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/PasswordResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordResetConfirm'
      tags:
      - users
    parameters: []
  /users/reset_username/:
    post:
      operationId: users_reset_username
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
      - users
    parameters: []
  /users/reset_username_confirm/:
    post:
      operationId: users_reset_username_confirm
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/UsernameResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/UsernameResetConfirm'
      tags:
      - users
    parameters: []
  /users/set_password/:
    post:
      operationId: users_set_password
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SetPassword'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SetPassword'
      tags:
      - users
    parameters: []
  /users/set_username/:
    post:
      operationId: users_set_username
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SetUsername'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SetUsername'
      tags:
      - users
    parameters: []
  /users/{id}/:
    get:
      operationId: users_read
      description: Кастомный вьюсет для работы с пользователем.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    put:
      operationId: users_update
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUser'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    patch:
      operationId: users_partial_update
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUser'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    delete:
      operationId: users_delete
      description: Кастомный вьюсет для работы с пользователем.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
  /users/{id}/add-friend/:
    post:
      operationId: users_add_friend
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUser'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
  /users/{id}/approved/:
    post:
      operationId: users_approve_request
      description: Кастомный вьюсет для работы с пользователем.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUser'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CustomUser'
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
  /users/{id}/delete-friend/:
    delete:
      operationId: users_delete_friend
      description: Кастомный вьюсет для работы с пользователем.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
  /users/{id}/delete-request/:
    delete:
      operationId: users_delete_request
      description: Кастомный вьюсет для работы с пользователем.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
definitions:
  TokenObtainPair:
    required:
    - username
    - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  TokenRefresh:
    required:
    - refresh
    type: object
    properties:
      refresh:
        title: Refresh
        type: string
        minLength: 1
      access:
        title: Access
        type: string
        readOnly: true
  TokenVerify:
    required:
    - token
    type: object
    properties:
      token:
        title: Token
        type: string
        minLength: 1
  Tag:
    required:
    - name
    - slug
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      name:
        title: Название
        description: Введите название
        type: string
        maxLength: 50
        minLength: 1
      color:
        title: Цвет
        type: string
        pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
        maxLength: 18
        minLength: 1
      slug:
        title: Ссылка
        type: string
        format: slug
        pattern: ^[-a-zA-Z0-9_]+$
        maxLength: 50
        minLength: 1
  CustomUser:
    required:
    - email
    - username
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      email:
        title: E-mail
        description: Введите ваш e-mail
        type: string
        format: email
        maxLength: 254
        minLength: 1
      username:
        title: Логин
        description: Введите логин
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 100
        minLength: 1
      first_name:
        title: Имя
        description: Введите имя
        type: string
        maxLength: 100
      last_name:
        title: Фамилия
        description: Введите фамилию
        type: string
        maxLength: 100
  CustomUserCreate:
    required:
    - email
    - username
    - password
    type: object
    properties:
      email:
        title: E-mail
        description: Введите ваш e-mail
        type: string
        format: email
        maxLength: 254
        minLength: 1
      username:
        title: Логин
        description: Введите логин
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 100
        minLength: 1
      first_name:
        title: Имя
        description: Введите имя
        type: string
        maxLength: 100
      last_name:
        title: Фамилия
        description: Введите фамилию
        type: string
        maxLength: 100
      password:
        title: Password
        type: string
        minLength: 1
      gender:
        title: Пол
        description: Укажите ваш пол
        type: string
        enum:
        - male
        - female
  Activation:
    required:
    - uid
    - token
    type: object
    properties:
      uid:
        title: Uid
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
  SendEmailReset:
    required:
    - email
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
  PasswordResetConfirm:
    required:
    - uid
    - token
    - new_password
    type: object
    properties:
      uid:
        title: Uid
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
      new_password:
        title: New password
        type: string
        minLength: 1
  UsernameResetConfirm:
    required:
    - new_email
    type: object
    properties:
      new_email:
        title: E-mail
        description: Введите ваш e-mail
        type: string
        format: email
        maxLength: 254
        minLength: 1
  SetPassword:
    required:
    - new_password
    - current_password
    type: object
    properties:
      new_password:
        title: New password
        type: string
        minLength: 1
      current_password:
        title: Current password
        type: string
        minLength: 1
  SetUsername:
    required:
    - current_password
    - new_email
    type: object
    properties:
      current_password:
        title: Current password
        type: string
        minLength: 1
      new_email:
        title: E-mail
        description: Введите ваш e-mail
        type: string
        format: email
        maxLength: 254
        minLength: 1
